In [2]:
import numpy as np

In [3]:
# Method 1
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [4]:
# Method 2
a=np.array([-1,1])
b=np.array([1,1])
np.dot(a,b) 

0

In [5]:
# Method 3
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [6]:
# Method 4
a = np.linspace(-10,10,5)
a

array([-10.,  -5.,   0.,   5.,  10.])

In [7]:
# Method 5
a = np.array([1, 2, 3, 4, 5, 6])
np.sum(a) 

21

In [8]:
# Method 6
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [9]:
# Method 7
a = np.arange(0,35)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34])

In [10]:
# Method 8
a = np.exp(5)
a

148.4131591025766

In [11]:
# Method 9
a = np.array([1,1])
a.sum() 

2

In [12]:
# Method 10
a = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])
b = a.copy()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [13]:
# Method 11
a = np.array([4, 5, 3, 9, 0, 2, 8, 6, 1, 2, 7])
a.sort()
a


array([0, 1, 2, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# Method 12
x = np.array([1,2,3,4,5,6])
x = x.std()
x

1.707825127659933

In [15]:
# Method 13
x = np.array([1,2,3,4,5,6])
max_x = x.max()
max_x

6

In [16]:
# Method 14
x = np.array([1,2,3,4,5,6])
min_x = x.min()
min_x

1

In [17]:
# Method 15
a = np.pi
a

3.141592653589793

In [18]:
# Method 16
x = np.array([1,2,3,4,5,6])
y = np.sin(x)
y

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ])

In [19]:
# Method 17
my_rand = np.random.rand (5)
my_rand 

array([0.93705323, 0.47509944, 0.93137989, 0.23400547, 0.04347172])

In [20]:
# Method 18
a = np.array([1,2,3,4,5,6])
log_a = np.log(a)
log_a

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947])

In [21]:
# Method 19
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
# Method 20
np.random.random(5)

array([0.16630781, 0.94591541, 0.99017661, 0.35154128, 0.32186236])

In [23]:
# Method 21
np.random.randint(0,100,10)

array([12,  0,  3, 25, 39, 21, 78, 96, 92, 28])

In [24]:
# Method 22
a = np.arange(25)
a = a.reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
# Method 23
a = np.array([1,2,3,4,5,6])
a = np.exp(a)
a

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 , 403.42879349])

In [26]:
# Method 24
a = np.array([1,2,3,4,5,6])
a = np.sqrt(a)
a

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [27]:
# Method 25
a = np.array([1,2,3,4,5,6])
a = np.mean(a)
a

3.5

In [28]:
# Method 26
a = np.array([1,2,3,4,5,6])
a = np.var(a)
a

2.9166666666666665

In [29]:
# Method 27
a = np.array([1,2,3,4,5,6])
a = np.cov(a)
a

array(3.5)

In [30]:
# Method 28
a = np.array([1,2,3,4,5,6])
a = np.diag(a)
a

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [31]:
# Method 29
a = np.array([[1,2,3],[4,5,6]])
a = np.vsplit(a,2)
a

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [32]:
# Method 30
a = np.array([[1,2,3],[4,5,6]])
a = np.vstack(a)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
# Method 31
a = np.array([[1,2,3],[4,5,6]])
a = np.hstack(a)
a

array([1, 2, 3, 4, 5, 6])

In [34]:
# Method 32
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[4,5,6],[1,2,3]])
c = np.add(a,b)
c

array([[5, 7, 9],
       [5, 7, 9]])

In [35]:
# Method 33
a = np.repeat(2015,10)
a

array([2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015])

In [38]:
# Method 34
a = np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

In [39]:
# Method 35
a = np.array([[1,2,3],[4,5,6]])
np.size(a)

6

In [40]:
# Method 36
a = np.array([[1,2,3],[4,5,6]])
np.info(a)

class:  ndarray
shape:  (2, 3)
strides:  (12, 4)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x1dfade3e580
byteorder:  little
byteswap:  False
type: int32


In [41]:
# Method 37
np.power(3,2)

9

In [42]:
# Method 38
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.transpose(a)


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [43]:
# Method 39
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.linalg.svd(a)


(array([[-0.21483724,  0.88723069,  0.40824829],
        [-0.52058739,  0.24964395, -0.81649658],
        [-0.82633754, -0.38794278,  0.40824829]]),
 array([1.68481034e+01, 1.06836951e+00, 1.47280825e-16]),
 array([[-0.47967118, -0.57236779, -0.66506441],
        [-0.77669099, -0.07568647,  0.62531805],
        [ 0.40824829, -0.81649658,  0.40824829]]))

In [44]:
# Method 40
a = np.array([[1.75,2.45,3.54],[4.12,5.65,6.32],[7.81,8.99,9.47]])
np.around(a)


array([[2., 2., 4.],
       [4., 6., 6.],
       [8., 9., 9.]])

In [45]:
# Method 41
x = np.array([1,2,3,4,5,6])
z = np.array([7,8,9,10,11,12])
zx = np.multiply(z,x)
zx

array([ 7, 16, 27, 40, 55, 72])

In [48]:
# Method 42
a = np.full((2,2),7) 
a

array([[7, 7],
       [7, 7]])

In [52]:
# Method 43
a = np.empty([2,2])
a

array([[-10.,  -5.],
       [  5.,  10.]])

In [54]:
# Method 44
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a = np.ravel(a)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
# Method 45
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a = np.delete(a, 0, axis=0)
a

array([[4, 5, 6],
       [7, 8, 9]])

In [63]:
# Method 46
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a = a.cumsum(axis=0)
a

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [66]:
# Method 47
a = np.array([1, 2, 3])
a = x.repeat(5)
a

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3])

In [75]:
# Method 48 
a = np.mat([[1, 2],[3, 4]])
a

matrix([[1, 2],
        [3, 4]])

In [77]:
# Method 49
a = np.array([1, 2, 2, 2, 3, 4, 5, 5, 6, 7, 8, 9])
np.median(a)

4.5

In [92]:
# Method 50
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.array_equal(a, b)


False